services:
  traefik:
    image: traefik:v3.6
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - preview-net
    restart: unless-stopped

networks:
  preview-net:
    name: preview-net
